# configs/pipeline_config.yaml
dataset:
  name: "nuscenes-mini"
  raw_path: "./data/raw_nuscenes"
  processed_path: "./data/processed"
  split_proportions:
    train: 0.70
    validation: 0.15
    test: 0.15

detector:
  model_name: "centerpoint"       # Updated
  classes: ["car"]
  confidence_threshold: 0.40